# config.yaml
name: "Audio Mixer Service"
description: "A persistent service that listens for requests to generate audio files."
version: "6.0.0" # A new architecture deserves a new major version
slug: "mix_audio_ducking"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
# This is the key change: we tell HA this is a long-running service
startup: "services"
init: false

audio: true
map:
  - share:rw
  - media:rw

options:
  elevenlabs_api_key: "YOUR_ELEVENLABS_API_KEY"
  voice_id: "21m00Tcm4TlvDq8ikWAM"
  music_filename: "/media/sounds/ambient_story_1.mp3"
  text_to_speak: "This is a test run of the new Pydub-based add-on."
  output_filename: "/media/local/pydub_mix.mp3"

schema:
  elevenlabs_api_key: "str"
  voice_id: "str"
  music_filename: "str"
  text_to_speak: "str"
  output_filename: "str"