# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Audio Mixer with Pydub"
description: "Generates TTS and mixes it with music using Pydub. Output is saved to /media."
version: "5.0.0" # Nová architektura, nová hlavní verze
slug: "mix_audio_ducking"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "application"
init: false
audio: true
map:
  - share:rw
  - media:rw

options:
  elevenlabs_api_key: "YOUR_ELEVENLABS_API_KEY"
  voice_id: "21m00Tcm4TlvDq8ikWAM"
  music_filename: "/media/sounds/ambient_story_1.mp3"
  text_to_speak: "This is a test run of the new Pydub-based add-on."
  output_filename: "/media/local/pydub_mix.mp3"

schema:
  elevenlabs_api_key: "str"
  voice_id: "str"
  music_filename: "str"
  text_to_speak: "str"
  output_filename: "str"