# config.yaml
name: "Audio Mixer Bash Service"
description: "A service that generates audio by listening for jobs on stdin, orchestrated by Bash."
version: "6.0.0" # Final architecture
slug: "mix_audio_ducking"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: "services"
init: false
map:
  - share:rw
  - media:rw

# Options here act as DEFAULTS. They can be overridden by the HA script.
options:
  elevenlabs_api_key: "YOUR_ELEVENLABS_API_KEY"
  voice_id: "21m00Tcm4TlvDq8ikWAM"
  music_filename: "/media/sounds/ambient_story_1.mp3"
  text_to_speak: "This is a test run of the new Pydub-based add-on."
  output_filename: "/media/local/pydub_mix.mp3"

schema:
  elevenlabs_api_key: "str"
  voice_id: "str"
  music_filename: "str"
  text_to_speak: "str"
  output_filename: "str"